In [1]:
import numpy as np

# Criando a malha

Definindo as condições de contorno

In [39]:
potenciais = {'v1':10, 'v2':100, 'v3':40, 'v4':0}
ni=500
N=20      #No de divisoes em y
nx=1.5*N+1 #Número de nós em x
ny=N+1     #Número de nós em y


In [28]:
print(nx, ny)

31.0 21


Breve manipulação com arrays, para nos acostumarmos a trabalhar cm o numpy e descobrir como achar alguns valores estratégicos

In [27]:
matriz = np.array([[1, 2, 3, 8], [4, 5, 6, 7]])

print(matriz, '\n')

# Ao solicitar o tamanho de um dos termos da matriz, como em len(matriz[0]), estamos descobrindo o número de colunas da matriz
#, enquanto que ao escrevermos um comando como len(matriz), estamos descobrindo quantas listas há no nosso array, o que por
# consequência nos leva ao número de linhas da matriz.
print('Número de linhas da matriz:\t', len(matriz))
print('Número de colunas da matriz:\t', len(matriz[0]))

[[1 2 3 8]
 [4 5 6 7]] 

Número de linhas da matriz:	 2
Número de colunas da matriz:	 4


Criando a malha de acordo com as condições de contorno fornecidas

In [50]:
valor_inicial = 1

malha = valor_inicial * np.ones((int(ny), int(nx)))


Potenciais fixos

In [51]:
# Descobrindo o número de linhas e colunas da matriz
n_linhas = len(malha)
n_colunas = len(malha[0])

# Estabelecendo as condições de contorno para os "lados" do retângulo
malha[n_linhas - 1, :] *= potenciais['v1']
malha[:, n_colunas - 1] *= potenciais['v2']
malha[0, :] *= potenciais['v3']
malha[:, 0] *= potenciais['v4']

# Os vértices acabam recebendo valores fora de escala, pois receberão acões duas vezes no código anterior
# Para consertar isso, fazemos a média entre as condições de contorno adjacentes a cada um dos vértices, sendo
# estes pontos de descontinuidade
malha[0, 0] = (malha[0, 1] + malha[1, 0]) / 2
malha[n_linhas - 1, 0] = (malha[n_linhas - 2, 0] + malha[n_linhas - 1, 1]) / 2
malha[0, n_colunas - 1] = (malha[0, n_colunas - 2] + malha[1, n_colunas - 1]) / 2
malha[n_linhas - 1, n_colunas - 1] = (malha[n_linhas - 2, n_colunas - 1] + malha[n_linhas - 1, n_colunas - 2]) / 2

In [58]:
descontinuidades = [malha[0, 0], malha[n_linhas - 1, 0], malha[n_linhas - 1, n_colunas - 1], malha[0, n_colunas - 1]]

print('Valores de descontinuidades após a transformação do último bloco de código:')
for i in descontinuidades:
    print(i)

Valores de descontinuidades após a transformação do último bloco de código:
20.0
5.0
55.0
70.0


In [57]:
malha[0]

array([20., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40., 40.,
       40., 40., 40., 40., 70.])